"""tenants payments notifications

Revision ID: 4cf44aef134f
Revises: 13ac9a72398f
Create Date: 2026-03-11 09:21:09.071671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4cf44aef134f'
down_revision: Union[str, Sequence[str], None] = '13ac9a72398f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.drop_column('properties', 'total_units')
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.drop_column('tenants', 'move_out_date')
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'national_id')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'notes')
    op.drop_column('tenants', 'rent_override')
    op.drop_column('tenants', 'deposit_amount')
    op.drop_column('tenants', 'full_name')
    op.drop_column('tenants', 'lease_start')
    op.drop_column('tenants', 'created_at')
    op.drop_column('tenants', 'deposit_paid_date')
    op.drop_column('tenants', 'deposit_paid')
    op.drop_column('tenants', 'is_active')
    op.drop_column('tenants', 'lease_end')
    op.drop_column('tenants', 'emergency_phone')
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'emergency_name')
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        sa.Enum(
            "bedsitter",
            "one_bedroom",
            "two_bedroom",
            "three_bedroom",
            "studio",
            "shop",
            "office",
            "other",
            name="unittype",
        ).create(bind, checkfirst=True)
        sa.Enum(
            "vacant",
            "occupied",
            "maintenance",
            name="unitstatus",
        ).create(bind, checkfirst=True)
        op.execute(
            sa.text(
                "ALTER TABLE units ALTER COLUMN unit_type TYPE unittype "
                "USING unit_type::unittype"
            )
        )
        op.execute(
            sa.text(
                "ALTER TABLE units ALTER COLUMN rent_amount TYPE numeric(12,2) "
                "USING NULLIF(trim(rent_amount::text), '')::numeric"
            )
        )
        op.execute(
            sa.text(
                "ALTER TABLE units ALTER COLUMN status TYPE unitstatus "
                "USING status::unitstatus"
            )
        )
        op.execute(
            sa.text(
                "ALTER TABLE units ALTER COLUMN amenities TYPE json USING "
                "CASE WHEN amenities IS NULL OR btrim(amenities::text) = '' "
                "THEN NULL::json ELSE amenities::json END"
            )
        )
    else:
        from sqlalchemy.dialects import mysql

        sa.Enum(
            "bedsitter",
            "one_bedroom",
            "two_bedroom",
            "three_bedroom",
            "studio",
            "shop",
            "office",
            "other",
            name="unittype",
        ).create(bind, checkfirst=True)
        sa.Enum(
            "vacant",
            "occupied",
            "maintenance",
            name="unitstatus",
        ).create(bind, checkfirst=True)
        op.alter_column(
            "units",
            "unit_type",
            existing_type=mysql.VARCHAR(length=50),
            type_=sa.Enum(
                "bedsitter",
                "one_bedroom",
                "two_bedroom",
                "three_bedroom",
                "studio",
                "shop",
                "office",
                "other",
                name="unittype",
            ),
            existing_nullable=True,
        )
        op.alter_column(
            "units",
            "rent_amount",
            existing_type=mysql.VARCHAR(length=32),
            type_=sa.Numeric(precision=12, scale=2),
            existing_nullable=False,
        )
        op.alter_column(
            "units",
            "status",
            existing_type=mysql.VARCHAR(length=32),
            type_=sa.Enum("vacant", "occupied", "maintenance", name="unitstatus"),
            existing_nullable=True,
        )
        op.alter_column(
            "units",
            "amenities",
            existing_type=mysql.TEXT(),
            type_=sa.JSON(),
            existing_nullable=True,
        )
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_unique_constraint('uq_unit_in_property', 'units', ['property_id', 'unit_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_unit_in_property', 'units', type_='unique')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.alter_column('units', 'amenities',
               existing_type=sa.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('units', 'status',
               existing_type=sa.Enum('vacant', 'occupied', 'maintenance', name='unitstatus'),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('units', 'rent_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('units', 'unit_type',
               existing_type=sa.Enum('bedsitter', 'one_bedroom', 'two_bedroom', 'three_bedroom', 'studio', 'shop', 'office', 'other', name='unittype'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('tenants', sa.Column('emergency_name', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('emergency_phone', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('lease_end', sa.DATE(), nullable=True))
    op.add_column('tenants', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('tenants', sa.Column('deposit_paid', sa.Boolean(), nullable=True))
    op.add_column('tenants', sa.Column('deposit_paid_date', sa.DATE(), nullable=True))
    op.add_column('tenants', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('lease_start', sa.DATE(), nullable=False))
    op.add_column('tenants', sa.Column('full_name', sa.String(length=200), nullable=False))
    op.add_column('tenants', sa.Column('deposit_amount', sa.String(length=32), nullable=True))
    op.add_column('tenants', sa.Column('rent_override', sa.String(length=32), nullable=True))
    op.add_column('tenants', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('tenants', sa.Column('national_id', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('move_out_date', sa.DATE(), nullable=True))
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.add_column('properties', sa.Column('total_units', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    # ### end Alembic commands ###
